/**
 * Shared wall/opening geometry math for every 3D view (working overlay
 * and Showcase Mode). Extracted from WiringOverlay3D so both views cut
 * walls and place parametric openings from one source — a door frame
 * generated by opening-geometry.ts lines up with the wall gap because
 * both derive from the same wallFrame()/wallBoxes() numbers.
 */
import { Opening, Wall } from "./api-client";

export const WALL_HEIGHT = 2.7;
export const CONDUIT_HEIGHT = 2.5;
export const DOOR_HEIGHT = 2.1;
export const WINDOW_SILL = 0.9;
export const WINDOW_HEAD = 2.1;

export interface WallFrame {
  length: number;
  /** Plan-space angle of the wall run (atan2 of end-start). */
  angle: number;
  /** Unit vector along the wall in plan space. */
  ux: number;
  uy: number;
  thickness: number;
}

/** Length/angle/direction of a wall, or null for a zero-length wall. */
export function wallFrame(wall: Wall): WallFrame | null {
  const dx = wall.end.x - wall.start.x;
  const dy = wall.end.y - wall.start.y;
  const length = Math.hypot(dx, dy);

  if (length === 0) return null;

  return {
    length,
    angle: Math.atan2(dy, dx),
    ux: dx / length,
    uy: dy / length,
    thickness: wall.thickness ?? 0.15,
  };
}

export interface WallBox {
  from: number;
  to: number;
  bottom: number;
  top: number;
}

/**
 * Solid wall segments after cutting door/window openings: doors leave a
 * lintel above DOOR_HEIGHT, windows leave a sill band below WINDOW_SILL
 * and a head band above WINDOW_HEAD.
 */
export function wallBoxes(wall: Wall, openings: Opening[]): WallBox[] {
  const frame = wallFrame(wall);

  if (!frame) return [];
  const length = frame.length;
  const sorted = openings
    .filter((opening) => opening.wallId === wall.id)
    .sort((a, b) => a.offset - b.offset);

  const boxes: WallBox[] = [];
  let cursor = 0;

  for (const opening of sorted) {
    const from = Math.max(0, Math.min(opening.offset, length));
    const to = Math.max(0, Math.min(opening.offset + opening.width, length));

    if (from > cursor) {
      boxes.push({ from: cursor, to: from, bottom: 0, top: WALL_HEIGHT });
    }
    if (opening.kind === "door") {
      boxes.push({ from, to, bottom: DOOR_HEIGHT, top: WALL_HEIGHT });
    } else {
      boxes.push({ from, to, bottom: 0, top: WINDOW_SILL });
      boxes.push({ from, to, bottom: WINDOW_HEAD, top: WALL_HEIGHT });
    }
    cursor = Math.max(cursor, to);
  }
  if (cursor < length) {
    boxes.push({ from: cursor, to: length, bottom: 0, top: WALL_HEIGHT });
  }

  return boxes;
}
